<a href="https://colab.research.google.com/github/cz101/ML-TF/blob/main/TF2_0_RNN_Shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf 
print(tf.__version__)

2.8.2


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.layers import  Input, Dense,SimpleRNN,Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

In [4]:
#creating the data set
T=10
D=3
N=1 
K=2 #number of outpit unit
X=np.random.randn(N,T,D)


print("X shape", X.shape)
print(X)

X shape (1, 10, 3)
[[[ 0.19983933  0.51387517  0.56484368]
  [ 1.78480972 -0.30657342  0.81179696]
  [ 1.0888688  -1.07945096  2.30384924]
  [ 1.26865692  0.05413945 -0.50055515]
  [ 0.14440991  1.49273257  1.30974684]
  [ 0.55445724 -0.34173593 -1.05053838]
  [ 0.26392309  1.00718277 -0.94329678]
  [-0.82519028 -0.06886508 -1.61305848]
  [-1.06163435 -0.77918497  0.27066325]
  [-1.38931047 -0.52516763  1.24663103]]]


In [5]:
#built the autogregressive RNN model
M=5 #hidden uinit
i= Input(shape=(T,D))
x=SimpleRNN(M)(i)
x= Dense(K)(x)
model = Model(i,x)


In [6]:
Yhat = model.predict(X)
print(Yhat)

[[ 0.32755783 -0.3249078 ]]


In [7]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn (SimpleRNN)      (None, 5)                 45        
                                                                 
 dense (Dense)               (None, 2)                 12        
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.layers[1].get_weights()

[array([[ 0.8551113 ,  0.47123045,  0.25462526,  0.12645471,  0.294946  ],
        [-0.54349625,  0.05702698, -0.51057744,  0.7024619 , -0.2772057 ],
        [-0.40602827,  0.7417808 ,  0.46210545,  0.7894313 , -0.2309143 ]],
       dtype=float32),
 array([[-0.32091033, -0.4520248 ,  0.70662284,  0.02746071,  0.43888533],
        [-0.42770702,  0.05273448, -0.05238787, -0.89306796, -0.11819838],
        [-0.10557074, -0.11326015, -0.6045481 , -0.02403175,  0.7810064 ],
        [-0.6548972 , -0.41702783, -0.33264148,  0.3608597 , -0.39538246],
        [-0.5234958 ,  0.778558  ,  0.14768548,  0.2662295 ,  0.16465259]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [9]:
a,b,c= model.layers[1].get_weights()
print(a.shape,b.shape,c.shape)

(3, 5) (5, 5) (5,)


In [10]:
Wx,Wh,bh = model.layers[1].get_weights()
Wo,bo=model.layers[2].get_weights()

In [11]:
from numpy.lib.stride_tricks import broadcast_arrays
h_last = np.zeros(M)
x =X[0]
Yhats= []

for t in range(T):
  h= np.tanh(x[t].dot(Wx)+ h_last.dot(Wh)+bh)
  y= h.dot(Wo)+bo
  Yhats.append(y)

  h_last =h
  
print(Yhats[-1])

[ 0.32755781 -0.32490795]
